### ISSUE TITLE
Email completely broken

### ISSUE THREAD

**Issue by ebonweaver** [UCSCLibrary/ContributorContact#3]
The plugin fails in two ways:
1. The email it sends comes from www-data@server instead of the admin account, specifically the account that was set up to send emails in the Contributions plugin, which this is extending.
2. It prevents making anything public.  It spits a page that is the info that should be used to make the email, the item is not actually made public, despite the guest user having been told it was.  There is no way to make a contributed item public while this plugin is active, so it's pretty much a total bust.

Apparently the plugin was broken since release http://omeka.org/forums-legacy/topic/contributions-plugin-making-items-public but has never been fixed.  Any hope of getting this in working condition?

**Comment by NedHenry** [comment]
Thank you for reporting this here. That issue had not yet been brought to my attention; it was listed on the Omeka forum as a problem with the ContributorContact plugin. I will investigate the issue and let you know how soon to expect an update to our plugin.

**Comment by NedHenry** [comment]
This was indeed a major bug. It was recently fixed this in 379e1eb162f4d8ea167deeca7a3e2ccbd720d028

**Comment by swatkins79** [comment]
Hi Ned,I was doing some volunteer work a couple of years ago for the Grateful Dead Archive Online project, but I'm no longer actively involved. I had GitHub access to look into upgrading Omeka at one point, but shouldn't have that access any more. Is it possible for you to remove me from the UCSC Library github  instance or is that something I'd need to do? I may have been set up under my personal swatkins790@gmail account rather than my CSU Monterey Bay swatkins@csumb.edu account.Thanks for your help,--SteveSteve WatkinsCoordinator of Technology DevelopmentCSU Monterey Bay LibraryOn Feb 15, 2017 11:22 AM, Ned Henry <notifications@github.com> wrote:This was indeed a major bug. It was recently fixed this in 379e1eb
